name: Release

on:
  push:
    branches:
      - dev1
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install Poetry
        run: pip install poetry==1.4.0
      - name: Set Poetry in PATH and persist changes
        run: |
          $env:PATH += ';C:\Users\runneradmin\AppData\Roaming\Python\Scripts'; setx PATH $env:PATH
        shell: powershell
      - name: Clear Poetry cache
        run: poetry cache clear --all pypi
      - name: Verify Poetry installation
        run: poetry --version
      - name: Install dependencies
        run: poetry install --no-root --only main
      - name: Build executable
        run: poetry run pyinstaller .\main.spec
      - name: Move executable
        run: move .\dist\main.exe .\main.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release artifacts
          path: |
            main.exe
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
